### ISSUE TITLE
plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [zimmicz/qgis-attribute-transfer-plugin#2]
@zimmicz How different is the plugin from attribute painter.

**Comment by zimmicz** [comment]
If I got it right, the attibute painter lets you choose source and target features and transfer multiple attributes between them based on your **manual selection**. My plugin bulk transfers one attribute from source layer to target layer based on **feature distance**, e.g. the target features get their values from the source features being the closest to them. I don't think the plugins perform the same task.

**Comment by NyakudyaA** [comment]
@zimmicz I think it would it be nice to collaborate your efforts to one plugin so that we can have a single plugin that does attribute transfer. It could it be a separate tab on the attribute painter? What are your thoughts

**Comment by zimmicz** [comment]
I might give it a shot and ask the author about his thoughts on this
matter. I'll let you know.

**Comment by zimmicz** [comment]
Hi @enricofer, could you please share your opinion on what @NyakudyaA proposed? I'm the author of the Attribute Transfer plugin (writes attribute values from source to target layer based on feature proximity). It seems our two plugins have something in common (attribute related data manipulation). Do you think it is feasible to join our forces? Does the idea appeal to you?

**Comment by enricofer** [comment]
Hi all, thanks for the involvement. Apparently I don't find any real use case for having the the two plugin merged in one. The plugins have a very defined scope and field of use and I found that merging them in one could result a bit confusing for the user. But I am ready to change my point of view...

**Comment by zimmicz** [comment]
@enricofer thanks for your input! I have fairly similar point of view on this topic. Is there anything wrong with having the two of them available in the plugins repo @NyakudyaA?

**Comment by NyakudyaA** [comment]
@zimmicz I hear your arguments. We always try to combine plugins that have the same functionality so that users can have one place to go to achieve certain tasks. In this case I can proceed to test the plugin
